In [2]:
import pandas as pd
import numpy as np
df=pd.read_csv("IRIS.csv")
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
# # df.index
# df.columns
# df.shape
df.dtypes
# df.columns.values
# df.describe()
# df['sepal_length']
# df.iloc[:10,:1]
# df.isnull().any()
# df.sepal_length.isnull().sum()

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [4]:
df['petal_length']=df['petal_length'].astype("int")
df.dtypes
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5             1          0.2     Iris-setosa
1             4.9          3.0             1          0.2     Iris-setosa
2             4.7          3.2             1          0.2     Iris-setosa
3             4.6          3.1             1          0.2     Iris-setosa
4             5.0          3.6             1          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0             5          2.3  Iris-virginica
146           6.3          2.5             5          1.9  Iris-virginica
147           6.5          3.0             5          2.0  Iris-virginica
148           6.2          3.4             5          2.3  Iris-virginica
149           5.9          3.0             5          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

In [7]:
x = df.iloc[:,:4]

In [8]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
x_scaled = min_max_scaler.fit_transform(x)

In [10]:
df_normalized = pd.DataFrame(x_scaled)
df_normalized

            0         1         2         3
0    0.222222  0.625000  0.067797  0.041667
1    0.166667  0.416667  0.067797  0.041667
2    0.111111  0.500000  0.050847  0.041667
3    0.083333  0.458333  0.084746  0.041667
4    0.194444  0.666667  0.067797  0.041667
..        ...       ...       ...       ...
145  0.666667  0.416667  0.711864  0.916667
146  0.555556  0.208333  0.677966  0.750000
147  0.611111  0.416667  0.711864  0.791667
148  0.527778  0.583333  0.745763  0.916667
149  0.444444  0.416667  0.694915  0.708333

[150 rows x 4 columns]

In [11]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [12]:
label_encoder = preprocessing.LabelEncoder()
df['species'] = label_encoder.fit_transform(df['species'])

In [13]:
df['species'].unique()

array([0, 1, 2])

In [14]:
features_df = df.drop(columns=['species'])

In [15]:
enc = preprocessing.OneHotEncoder()
enc_df=pd.DataFrame(enc.fit_transform(df[['species']]).toarray())

In [16]:
df_encode = features_df.join(enc_df)
df_encode

     sepal_length  sepal_width  petal_length  petal_width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

In [17]:
df_encode.rename(columns = {0:'Iris-Setosa',
1:'Iris-Versicolor',2:'Iris-virginica'}, inplace = True)

In [18]:
df_encode

,sepal_length,sepal_width,petal_length,petal_width,Iris-Setosa,Iris-Versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

In [19]:
from sklearn import preprocessing
df['species'].unique()

array([0, 1, 2])

In [20]:
one_hot_df = pd.get_dummies(df, prefix="Species",
columns=['species'], drop_first=True)

In [21]:
one_hot_df

,sepal_length,sepal_width,petal_length,petal_width,Species_1,Species_2
0,5.1,3.5,1.4,0.2,False,False
1,4.9,3.0,1.4,0.2,False,False
2,4.7,3.2,1.3,0.2,False,False
3,4.6,3.1,1.5,0.2,False,False
4,5.0,3.6,1.4,0.2,False,False
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,False,True
146,6.3,2.5,5.0,1.9,False,True
147,6.5,3.0,5.2,2.0,False,True
148,6.2,3.4,5.4,2.3,False,True
149,5.9,3.0,5.1,1.8,False,True